package com.example.demo.model;

import io.swagger.annotations.ApiModelProperty;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document
public class Student {
    @Id
    @ApiModelProperty(notes = "Autogenerated student id", required = true)
    public String id;
    //    @ApiModelProperty(notes = "Student's username for logging in", required = true)
//    private String username;
//    @ApiModelProperty(notes = "Student's password for logging in", required = true)
//    private String password;
    @ApiModelProperty(notes = "Student's first name", required = true)
    private String firstName;
    @ApiModelProperty(notes = "Student's last name", required = true)
    private String lastName;
    @ApiModelProperty(notes = "Student's year in a school", required = false)
    private int year;
    @ApiModelProperty(notes = "Id of the student's school", required = false)
    private String schoolId;

    public Student() {
    }

    public Student(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.year = year;
        this.schoolId = schoolId;
    }


    public String getId() {
        return id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String name) {
        this.firstName = name;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year = year;
    }

    public String getSchoolId() {
        return schoolId;
    }

    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId;
    }

//    public String getPassword() {

    //        return password;
//    }
//    }
//
//    public void setPassword(String password) {
//        this.password = password;
//    }
//
//    public String getUsername() {
//        return username;}
//    public void setUsername(String username) {
//        this.username = username;
//    }

    @Override
    public String toString() {
        return "Student{" +
                "id=" + id +
                ", name='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", year='" + year + '\'' +
                '}';
    }
}
